version: "3.8"

services:
  henland-img:
    container_name: henland-img
    image: darthsim/imgproxy:latest
    #hostname:
    environment:
      - IMGPROXY_SOURCE_URL_PREFIX="https://ipfs.io/ipfs/"
    #command: sh -c ''
    restart: always
    #volumes:
    #  - ./tmp:/tmp
    ports:
      - 8011:8080
